---
http_interactions:
- request:
    method: get
    uri: https://api.tcgdex.net/v2/en/hp
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - tcgdex-ruby-sdk/0.1.0
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Access-Control-Allow-Headers:
      - DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range
      Access-Control-Allow-Methods:
      - GET,POST,OPTIONS
      Access-Control-Allow-Origin:
      - "*"
      Access-Control-Expose-Headers:
      - Content-Length,Content-Range
      Alt-Svc:
      - h3=":443"; ma=2592000
      Cache-Control:
      - no-cache, no-store, must-revalidate
      Content-Length:
      - '137'
      Content-Type:
      - application/json; charset=utf-8
      Date:
      - Tue, 14 Jul 2026 23:07:23 GMT
      Etag:
      - W/"89-x2x6imZGXP9evTwEaGwrQNblFis"
      Strict-Transport-Security:
      - max-age=31536000
      X-Powered-By:
      - Express
    body:
      encoding: UTF-8
      string: "[10,30,40,50,60,70,80,90,100,110,120,130,140,150,160,170,180,190,200,210,220,230,240,250,260,270,280,300,310,320,330,340,350,360,370,380]"
  recorded_at: Tue, 14 Jul 2026 23:07:23 GMT
recorded_with: VCR 6.4.0
